# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy ASP.Net Core app to Azure Web App - CofffeeShoManagement

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      # Publish API project
      - name: Publish API project
        run: dotnet publish CoffeeShopAPI/CoffeeShopAPI.csproj -c Release -o ${{env.DOTNET_ROOT}}/api

      # Publish Web project  
      - name: Publish Web project
        run: dotnet publish CoffeeShop/CoffeeShop.csproj -c Release -o ${{env.DOTNET_ROOT}}/web

      # Create combined directory and copy outputs
      - name: Create combined directory
        run: |
          mkdir -p ${{env.DOTNET_ROOT}}/combined
          cp -r ${{env.DOTNET_ROOT}}/api/* ${{env.DOTNET_ROOT}}/combined/
          mkdir -p ${{env.DOTNET_ROOT}}/combined/web
          cp -r ${{env.DOTNET_ROOT}}/web/* ${{env.DOTNET_ROOT}}/combined/web/

      # Create startup.sh file
      - name: Create startup.sh
        run: |
          echo '#!/bin/bash' > ${{env.DOTNET_ROOT}}/combined/startup.sh
          echo '# Start API on port 7197' >> ${{env.DOTNET_ROOT}}/combined/startup.sh
          echo 'dotnet /home/site/wwwroot/combined/CoffeeShopAPI.dll --urls=http://0.0.0.0:7197 &' >> ${{env.DOTNET_ROOT}}/combined/startup.sh
          echo '' >> ${{env.DOTNET_ROOT}}/combined/startup.sh
          echo '# Start Web on port 8080 (required by Azure)' >> ${{env.DOTNET_ROOT}}/combined/startup.sh
          echo 'dotnet /home/site/wwwroot/combined/web/CoffeeShop.dll --urls=http://0.0.0.0:8080' >> ${{env.DOTNET_ROOT}}/combined/startup.sh

      # Upload the combined artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/combined

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_62A37D5CEC324257A6D373F3B64BE012 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_16F4F1B968E3470E88C40169F15F4E37 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8FC8B0D293CA4CEFB110AD11ACDA5412 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CofffeeShoManagement'
          slot-name: 'Production'
          package: .
