name: Build and deploy ASP.Net Core app to Azure Web App - CofffeeShoManagement

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish API
        run: dotnet publish CoffeeShopAPI/CoffeeShopAPI.csproj -c Release -o ./publish

      - name: Publish Web
        run: dotnet publish CoffeeShop/CoffeeShop.csproj -c Release -o ./publish/web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_62A37D5CEC324257A6D373F3B64BE012 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_16F4F1B968E3470E88C40169F15F4E37 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8FC8B0D293CA4CEFB110AD11ACDA5412 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CofffeeShoManagement'
          slot-name: 'Production'
          package: .
